package com.entertainment;

public class InvalidBrandException extends Exception {

    // generated by cmd +n -> constructor (the first 4)
    public InvalidBrandException() {
        super();
    }

    public InvalidBrandException(String message) {
        super(message);
    }

    public InvalidBrandException(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidBrandException(Throwable cause) {
        super(cause);
    }
}